#!/bin/bash
# Docker & Docker Compose wrapper script

clear ()
{
  docker rm -f $(docker ps -aq)
  docker rmi -f $(docker images -aq)
}

build ()
{
  docker-compose build
}

start ()
{
  build

  # launch 5 instances of app
  # to run parallel tests
  docker-compose scale app=5
}

"$@"